// svelte/src/Select.svelte
<script lang="ts">
  export let value: string;
  export let options: string[] = [];
  export let name: string;
  export let label: string;
  export let onChange: (value: string) => void;

  const handleChange = (e: Event) =>
    onChange((e.target as HTMLSelectElement).value);
</script>

<div class="input-container">
  <label for={name}>{label}</label>
  <select id={name} {name} {value} on:change={handleChange}>
    {#each options as option}
      <option value={option}>{option}</option>}
    {/each}
  </select>
</div>

// solid/src/Select.tsx
import { For } from "solid-js";

type SelectProps = {
  label: string;
  name: string;
  options: string[];
  value: string;
  onChange: (value: string) => void;
};

export const Select = ({
  value,
  name,
  label,
  options,
  onChange,
}: SelectProps) => {
  return (
    <div class="input-container">
      <label for={name}>{label}</label>
      <select
        id={name}
        value={value}
        name={name}
        onChange={(e) => onChange?.(e.target.value)}
      >
        <For each={options}>
          {(option) => <option value={option}>{option}</option>}
        </For>
      </select>
    </div>
  );
};
